### ISSUE TITLE
Feature-Request: Continuous scrolling (ht16k33)

### ISSUE THREAD

**Issue by ShadyMCShadesen** [ssieb/esphome_components#35]
Hey, would it be possible to have a setting for continuous scrolling of the ht16k33_alpha display component. 🙂

Currently the scroll stops at the end of the text and jumps back to the start. The "continuous"-version would act a little different:
If the scrolling text comes to an end, the beginning is appended with some distance and stops briefly as soon as it has arrived at the beginning again. then the scroll continues and everything starts from the beginning

Probably with timing settings for the scroll and the pause

😊

**Comment by ShadyMCShadesen** [comment]
https://github.com/ssieb/custom_components/pull/36

**Comment by ssieb** [comment]
I have implemented this now, please test it out.
