### ISSUE TITLE
[analog_keypad] State is unknown until a button is pressed

### ISSUE THREAD

**Issue by ptr727** [ssieb/esphome_components#81]
Button state is reported as `Unknown` until a button is pressed, once that button is pressed the state changes to `on` or `off`.  
Expect button state to be default `off` when initialized, not `unknown`.

**Comment by ssieb** [comment]
Should be fixed with https://github.com/ssieb/esphome_components/commit/a41c9efb8e8a26db072523a3def15b10df7c3275.
